import hardcodedContent from "@/lib/blog-hardcoded-content.generated.json";

export type BlogSection = { id: string; title: string; html: string };

export type BlogPost = {
  id: string;
  slug: string;
  title: string;
  excerpt: string;
  image: string;
  imageAlt: string;
  author: string;
  date: string;
  readTime: string;
  category: string;
  tags: string[];
  sections: BlogSection[];
  relatedSlugs: string[];
  seoTitle: string;
  seoDescription: string;
  featured: boolean;
  published: boolean;
};

const content = hardcodedContent as Record<string, BlogSection[]>;

const summaries: Omit<BlogPost, "sections">[] = [
  { id:"solo-trekking-nepal-2026",slug:"solo-trekking-nepal-2026",title:"Solo Trekking in Nepal: Complete 2026 Guide for Independent Travelers",excerpt:"Solo trekking in Nepal is now legal again and safer than ever. From the best treks for solo travelers to permits, costs, and safety tips, here's everything you need to know to plan your solo Himalayan adventure in 2026.",image:"/images/used/solo-trek-blog-hero.webp",imageAlt:"Solo trekking in the Nepal Himalayas",author:"Sabinaya Dhakal",date:"August 7, 2026",readTime:"8 min",category:"Trekking Guide",tags:["Solo Trekking Nepal","Independent Trekking","Nepal Trek 2026","Solo Travel Nepal","Trekking Guide","Himkala Adventure"],relatedSlugs:["everest-vs-annapurna-base-camp","best-time-to-visit-nepal","best-beginner-treks-nepal"],seoTitle:"Solo Trekking in Nepal: Complete 2026 Guide for Independent Travelers",seoDescription:"Solo trekking in Nepal is legal again. Complete 2026 guide covering best treks, permits, costs, safety tips, and everything you need for a solo Himalayan adventure.",featured:true,published:true },
  { id:"nepal-trek-cost-2026",slug:"nepal-trek-cost-2026",title:"How Much Does a Nepal Trek Really Cost? Complete 2026 Budget Breakdown",excerpt:"Planning a trek in Nepal? Here's exactly how much it costs in 2026. From budget-friendly Poon Hill at $500 to premium Upper Mustang at $2,595. We break down every trek, permit, and hidden expense so you know what to budget.",image:"/images/used/nepal-trek-cost-blog-hero.webp",imageAlt:"Nepal trekking cost and budget guide",author:"Sabinaya Dhakal",date:"August 4, 2026",readTime:"16 min",category:"Trekking Guide",tags:["Trekking Cost Nepal","Budget Trekking Nepal","Everest Base Camp Cost","Annapurna Circuit Cost","Nepal Trek 2026","Himkala Adventure"],relatedSlugs:["solo-trekking-nepal-2026","everest-vs-annapurna-base-camp","best-time-to-visit-nepal"],seoTitle:"How Much Does a Nepal Trek Really Cost? Complete 2026 Budget Breakdown",seoDescription:"A complete 2026 Nepal trekking budget breakdown covering packages, permits and hidden expenses.",featured:false,published:true },
  { id:"everest-vs-annapurna-base-camp",slug:"everest-vs-annapurna-base-camp",title:"Everest Base Camp vs. Annapurna Base Camp: How To Decide Your Next Big Trek",excerpt:"Two major treks dominate every Nepal itinerary shortlist. Everest Base Camp is famous for the altitude and the realisation that you're standing at the foot of the world's tallest mountain. Annapurna Base Camp is famous for the scenery, the feeling of being swallowed whole by peaks on every side. Which one is right for you?",image:"/images/used/ebc-vs-abc.webp",imageAlt:"Everest Base Camp and Annapurna Base Camp comparison",author:"Meg Cassidy",date:"May 26, 2026",readTime:"16 min",category:"Trekking Guide",tags:["Everest Base Camp","Annapurna Base Camp","EBC vs ABC","Nepal Trekking","Trek Comparison","Himkala Adventure"],relatedSlugs:["solo-trekking-nepal-2026","nepal-trek-cost-2026","best-time-to-visit-nepal"],seoTitle:"Everest Base Camp vs. Annapurna Base Camp",seoDescription:"Compare Everest Base Camp and Annapurna Base Camp by altitude, cost, duration, scenery and difficulty.",featured:false,published:true },
  { id:"best-beginner-treks-nepal",slug:"best-beginner-treks-nepal",title:"5 Best Beginner Treks in Nepal: From Sunrise Hikes to Himalayan Valleys",excerpt:"Nepal has a trek for every level of experience. Despite its reputation for giant peaks and extreme altitudes, some of the most rewarding adventures are easily within reach for first-timers – with only a moderate level of fitness required. From single-day sunrise hikes to multi-day routes deep into the Himalayas, these five treks are the ones worth considering.",image:"/images/used/manaslu-main-page.webp",imageAlt:"Beginner trekking route in Nepal",author:"Meg Cassidy",date:"May 24, 2026",readTime:"14 min",category:"Trekking Guide",tags:["Beginner Treks","Nepal Trekking","Nagarkot","Poon Hill","Mardi Himal","Langtang","Namobuddha","Himkala Adventure"],relatedSlugs:["solo-trekking-nepal-2026","nepal-trek-cost-2026","everest-vs-annapurna-base-camp"],seoTitle:"5 Best Beginner Treks in Nepal",seoDescription:"Five accessible Nepal treks for beginners, from sunrise hikes to Himalayan valleys.",featured:false,published:true },
  { id:"tilicho-lake-sacred-trek",slug:"tilicho-lake-sacred-trek",title:"Tilicho Lake: The Sacred Himalayan Lake of Legends, Faith, and Adventure",excerpt:"Perched at 4,919 meters in the Annapurna region, Tilicho Lake is not just one of the highest lakes in the world, it is a place where Hindu mythology meets breathtaking natural beauty. Discover the ancient story of Kakbhusundi, the crow sage, and why thousands of pilgrims and trekkers make the arduous journey to its holy shores each year.",image:"/images/used/tilicho-blog.webp",imageAlt:"Sacred Tilicho Lake in the Annapurna region",author:"Sabinaya Dhakal",date:"May 20, 2026",readTime:"12 min",category:"Trekking & Pilgrimage",tags:["Tilicho Lake","Annapurna Circuit","Nepal Trekking","Hindu Pilgrimage","Kakbhusundi","Ramayana","Himkala Adventure"],relatedSlugs:["solo-trekking-nepal-2026","nepal-trek-cost-2026","everest-vs-annapurna-base-camp"],seoTitle:"Tilicho Lake: Sacred Himalayan Lake of Legends",seoDescription:"Discover Tilicho Lake's sacred legends, trek itinerary, packing list and best travel season.",featured:false,published:true },
  { id:"pigeons-symbol-peace-nepal",slug:"pigeons-symbol-peace-nepal",title:"From Sacred Messengers to 'Flying Rats': Why Nepalis Worship Pigeons While Europeans Shoo Them Away",excerpt:"In Kathmandu, pigeons are revered as divine ancestors and harbingers of peace. In London, they're pests. This stark cultural divide reveals deep truths about how we see nature, spirituality, and our place in the world. Discover the fascinating story behind Nepal's urban pigeons and what they teach us about coexistence.",image:"/images/used/dog-pigeons.webp",imageAlt:"Pigeons in Kathmandu, Nepal",author:"Sabinaya Dhakal",date:"May 9, 2026",readTime:"9 min",category:"Culture & Society",tags:["Pigeons","Nepal","Cultural Contrasts","Urban Wildlife","Symbolism","Hinduism","Himkala Adventure"],relatedSlugs:["solo-trekking-nepal-2026","nepal-trek-cost-2026","everest-vs-annapurna-base-camp"],seoTitle:"Why Nepalis Worship Pigeons While Europeans Shoo Them Away",seoDescription:"The cultural and religious meaning of pigeons in Nepal and their contrasting reputation in Europe.",featured:false,published:true },
  { id:"best-time-to-visit-nepal",slug:"best-time-to-visit-nepal",title:"When Should You Visit Nepal? A Month-by-Month Guide to Perfect Timing",excerpt:"From the rainbow blooms of spring to the crystal-clear skies of autumn, every season in Nepal offers something magical. But timing your visit right can mean the difference between watching Everest disappear behind clouds or standing beneath its glittering peak. Here's everything you need to know.",image:"/images/used/historic-scenic-photography-nepal.webp",imageAlt:"Nepal landscape during trekking season",author:"Sabinaya Dhakal",date:"May 7, 2026",readTime:"9 min",category:"Travel Guide",tags:["Best Time to Visit","Nepal Travel","Seasons","Trekking","Weather","Himkala Adventure"],relatedSlugs:["solo-trekking-nepal-2026","nepal-trek-cost-2026","everest-vs-annapurna-base-camp"],seoTitle:"Best Time to Visit Nepal: Month-by-Month Guide",seoDescription:"A month-by-month guide to Nepal's trekking weather, seasons and best travel experiences.",featured:false,published:true },
];

export const BLOG_POSTS_FALLBACK: BlogPost[] = summaries.map((post) => ({ ...post, sections: content[post.slug] || [] }));
export const BLOG_POSTS_UPDATED_EVENT = "himkala:blog-posts-updated";

export function createBlogPostId(title: string) { return title.toLowerCase().trim().replace(/[^a-z0-9]+/g,"-").replace(/^-+|-+$/g,"") || `article-${Date.now()}`; }
export function normalizeBlogPosts(value: unknown): BlogPost[] | null {
  if (!Array.isArray(value)) return null;
  const valid=value.every((item)=>{const post=item as Partial<BlogPost>;return typeof post.id==="string"&&typeof post.slug==="string"&&typeof post.title==="string"&&typeof post.excerpt==="string"&&typeof post.image==="string"&&typeof post.author==="string"&&typeof post.date==="string"&&typeof post.readTime==="string"&&typeof post.category==="string"&&Array.isArray(post.tags)&&Array.isArray(post.sections)&&Array.isArray(post.relatedSlugs)&&typeof post.featured==="boolean"&&typeof post.published==="boolean";});
  return valid&&new Set(value.map((item)=>(item as BlogPost).id)).size===value.length?value as BlogPost[]:null;
}
