"use client";

import * as React from "react";
import Head from "next/head";
import Image from "next/image";
import Link from "next/link";
import { ArrowRight, BookOpen, Calendar, Check, ChevronDown, Clock, Copy, Facebook, User } from "lucide-react";
import { Button } from "@/components/ui/button";
import { BLOG_POSTS_FALLBACK, BLOG_POSTS_UPDATED_EVENT, BlogPost } from "@/lib/blog-posts";
import { loadBlogPosts } from "@/lib/firebase/blog-posts-repository";

export default function BlogPostDetail({slug}:{slug:string}){
  const fallback=BLOG_POSTS_FALLBACK.find((item)=>item.slug===slug);
  const [post,setPost]=React.useState<BlogPost|undefined>(fallback);
  const [allPosts,setAllPosts]=React.useState(BLOG_POSTS_FALLBACK);
  const [copied,setCopied]=React.useState(false);
  const refresh=React.useCallback(()=>{void loadBlogPosts().then(({posts})=>{setAllPosts(posts);setPost(posts.find((item)=>item.slug===slug));});},[slug]);
  React.useEffect(()=>{refresh();window.addEventListener(BLOG_POSTS_UPDATED_EVENT,refresh);return()=>window.removeEventListener(BLOG_POSTS_UPDATED_EVENT,refresh);},[refresh]);
  if(!post||!post.published)return <main className="min-h-[60vh] bg-[#f2ede4] px-5 py-24 text-center"><h1 className="font-serif text-4xl text-[#14383b]">Article not available</h1><Link href="/blog" className="mt-5 inline-block text-sm font-bold text-[#cf6943]">Return to the journal</Link></main>;
  const related=post.relatedSlugs.map((relatedSlug)=>allPosts.find((item)=>item.slug===relatedSlug)).filter((item):item is BlogPost=>Boolean(item?.published));
  const copy=()=>{void navigator.clipboard.writeText(window.location.href);setCopied(true);window.setTimeout(()=>setCopied(false),2000);};
  const facebook=()=>window.open(`https://www.facebook.com/sharer/sharer.php?u=${encodeURIComponent(window.location.href)}`,"_blank","noopener,noreferrer");
  const scroll=(id:string)=>document.getElementById(id)?.scrollIntoView({behavior:"smooth",block:"start"});
  const readTime=post.readTime.toLowerCase().includes("read")?post.readTime:`${post.readTime} read`;
  return <><Head><title>{post.seoTitle||post.title}</title><meta name="description" content={post.seoDescription||post.excerpt}/><link rel="canonical" href={`https://www.himkalaadventure.com/blog/${post.slug}`}/><meta property="og:title" content={post.seoTitle||post.title}/><meta property="og:description" content={post.seoDescription||post.excerpt}/><meta property="og:image" content={`https://www.himkalaadventure.com${post.image}`}/><meta property="og:type" content="article"/></Head><div className="flex min-h-screen flex-col overflow-x-hidden bg-[#f2ede4]">
    <section className="bg-[#f2ede4] px-4 py-12 sm:px-5 sm:py-16 md:px-8 md:py-20 lg:py-28"><div className="mx-auto max-w-[880px]"><div className="flex flex-col gap-4 md:flex-row md:items-end md:justify-between md:gap-8"><div><div className="flex items-center gap-2 text-[10px] font-semibold uppercase tracking-[.12em] text-[#cf6943] sm:text-xs"><span className="h-px w-6 bg-[#cf6943] sm:w-8"/><span>{post.category}</span></div><h1 className="mt-3 font-serif text-[clamp(2.5rem,8vw,5rem)] leading-[1.05] tracking-[-.03em] text-[#14383b] sm:mt-5 sm:leading-[.95] sm:tracking-[-.045em]">{post.title}</h1></div><div className="max-w-full md:max-w-[280px]"><p className="text-sm leading-6 text-[#66706d]">{post.excerpt}</p><div className="mt-3 flex flex-wrap items-center gap-2"><span className="rounded bg-[#cf6943] px-3 py-1 text-[10px] font-bold tracking-wide text-[#fff8ee]">{readTime}</span><span className="rounded border border-[#d8cec0]/30 bg-[#f7f2e9] px-3 py-1 text-[10px] font-bold tracking-wide text-[#14383b]">{post.date}</span></div></div></div><div className="mt-6 flex flex-wrap items-center justify-between gap-3 border-t border-[#d8cec0]/30 pt-6"><div className="flex items-center gap-3 text-sm text-[#66706d]"><span className="flex h-8 w-8 items-center justify-center rounded-full border border-[#d8cec0]/30 bg-[#e4d8c8]"><User className="h-4 w-4 text-[#cf6943]"/></span><span className="font-medium text-[#14383b]">{post.author}</span></div><div className="flex gap-2"><button onClick={facebook} className="rounded-full bg-[#e4d8c8] p-2 hover:bg-[#d8cec0]" aria-label="Share on Facebook"><Facebook className="h-4 w-4"/></button><button onClick={copy} className="rounded-full bg-[#e4d8c8] p-2 hover:bg-[#d8cec0]" aria-label="Copy link">{copied?<Check className="h-4 w-4 text-[#cf6943]"/>:<Copy className="h-4 w-4"/>}</button></div></div></div></section>
    <section className="border-b border-[#d8cec0]/30 bg-[#f2ede4] px-4 py-6 sm:px-5 sm:py-8 md:px-8"><div className="mx-auto max-w-[880px]"><details className="group"><summary className="flex cursor-pointer list-none items-center justify-between"><span className="flex items-center gap-2 text-xs font-semibold uppercase tracking-wider text-[#66706d]"><BookOpen className="h-4 w-4 text-[#cf6943]"/>Table of Contents</span><ChevronDown className="h-4 w-4 text-[#66706d] transition-transform group-open:rotate-180"/></summary><nav className="mt-4 grid grid-cols-2 gap-1 sm:grid-cols-3 sm:gap-2">{post.sections.map((section)=><button key={section.id} onClick={()=>scroll(section.id)} className="rounded-lg px-3 py-2 text-left text-xs text-[#556363] hover:bg-[#e4d8c8] hover:text-[#cf6943] sm:text-sm">{section.title}</button>)}</nav></details></div></section>
    <section className="bg-[#f2ede4] px-4 py-8 sm:px-5 sm:py-12 md:px-8 md:py-16 lg:py-20"><div className="mx-auto max-w-[880px]"><article className="prose prose-sm max-w-none prose-slate prose-headings:font-serif prose-headings:leading-tight prose-headings:tracking-[-.02em] prose-headings:text-[#14383b] prose-a:text-[#cf6943] prose-a:no-underline prose-strong:text-[#14383b] hover:prose-a:underline sm:prose-base">{post.sections.map((section,index)=><section key={section.id} id={section.id} className="mb-6 scroll-mt-20 sm:mb-8 md:mb-12">{index>0&&<h2 className="mb-3 font-serif text-xl tracking-[-.025em] text-[#14383b] sm:mb-4 sm:text-2xl md:text-3xl lg:text-4xl">{section.title}</h2>}<div dangerouslySetInnerHTML={{__html:section.html}}/></section>)}<div className="mt-6 flex flex-wrap gap-2">{post.tags.map((tag)=><span key={tag} className="rounded-full border border-[#d8cec0] px-3 py-1 text-xs text-[#556363]">#{tag}</span>)}</div></article><div className="mt-10 flex flex-col items-start justify-between gap-4 border-t border-[#d8cec0]/50 pt-8 sm:flex-row sm:items-center"><p className="text-sm text-[#66706d]">Enjoyed this article? Share it with fellow adventurers.</p><div className="flex gap-2"><Button size="sm" onClick={facebook} className="bg-[#1877f2] text-white"><Facebook className="mr-1.5 h-3.5 w-3.5"/>Share</Button><Button size="sm" variant="outline" onClick={copy}>{copied?<Check className="mr-1.5 h-3.5 w-3.5"/>:<Copy className="mr-1.5 h-3.5 w-3.5"/>}{copied?"Copied!":"Copy Link"}</Button></div></div></div></section>
    <section className="bg-[#e4d8c8] px-4 py-12 sm:px-5 sm:py-16 md:px-8 md:py-20 lg:py-28"><div className="mx-auto max-w-[880px]"><div className="mb-8 flex flex-col gap-4 md:flex-row md:items-end md:justify-between md:gap-8"><div><p className="text-[10px] font-semibold uppercase tracking-[.12em] text-[#cf6943] sm:text-xs">Continue Your Journey</p><h2 className="mt-2 font-serif text-[clamp(1.8rem,4vw,4rem)] leading-[1.05] tracking-[-.03em] text-[#14383b] sm:mt-3 sm:leading-[.95]">More Insights <span className="text-[#cf6943]">from Us</span></h2></div><Link href="/blog" className="flex items-center gap-2 border-b border-[#cf6943] pb-1 text-[10px] font-bold tracking-[.14em] text-[#cf6943]">VIEW ALL <ArrowRight className="h-3 w-3"/></Link></div><div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-3">{related.map((item)=><Link href={`/blog/${item.slug}`} key={item.id} className="group overflow-hidden rounded-lg bg-[#f7f2e9] shadow-sm"><div className="relative h-48 overflow-hidden sm:h-56"><Image src={item.image} alt={item.imageAlt||item.title} fill className="object-cover opacity-85 transition-transform duration-500 group-hover:scale-[1.02]" sizes="(max-width:640px) 100vw, 33vw"/></div><div className="p-5"><h3 className="line-clamp-2 font-bold leading-snug text-[#14383b] group-hover:text-[#cf6943]">{item.title}</h3><div className="mt-3 flex gap-3 text-xs text-[#556363]"><span className="flex items-center gap-1"><Calendar className="h-3 w-3"/>{item.date}</span><span className="flex items-center gap-1"><Clock className="h-3 w-3"/>{item.readTime}</span></div></div></Link>)}</div></div></section>
  </div></>;
}
